### ISSUE TITLE
rgdal/rgeos retirement?

### ISSUE THREAD

**Issue by CCheCastaldo** [joaofgoncalves/SegOptim#6]
Hi, I was wondering how you are planning to handle the [upcoming retirement of rgdal/rgeos](https://r-spatial.org/r/2022/04/12/evolution.html)? I see that rgdal (and raster) are dependencies of SegOptim and I worry this package will no longer be functional after they are gone.

**Comment by joaofgoncalves** [comment]
Hi Christian, 
Honestly, I still don't have a clear roadmap for doing a package reshape, mainly due to the lack of time.

Many functions have to be completely modified and re-implemented now with terra and sf. Although this provides an opportunity for improvement, it also demands quite some time. I think, maybe within 4 to 6 months, the package will have a new version compatible with this change which is OK given the retirement plans for rgdal and rgeos. 

Can I ask why you are interested in this issue? Are you using SegOptim actively? Would you like to collaborate on the project?  

Cheers
